CREATE TABLE TB_USERS (
    ID INT IDENTITY(1,1),
    USERNAME NVARCHAR(255) NOT NULL UNIQUE,
    PASSWORD_HASH NVARCHAR(255) NOT NULL, 
    CREATED_AT DATETIME DEFAULT GETDATE()
);

ALTER TABLE TB_USERS
ADD CONSTRAINT PK_TB_USERS_ID PRIMARY KEY (ID);